const FALLBACK_PROFILE={identity:{name:"Simone Laraia",company:"AUNDE Italia",logo:"assets/logo/ultimo-logo.png",themeColor:"#233F91"},branding:{logo:"assets/logo/ultimo-logo.png",company:"AUNDE Italia",website:"https://aunde.com"},role:{departmentIt:"Ente Tecnico",departmentEn:"Technical Department",titleIt:"Tecnico di termoformatura",titleEn:"Fabric Thermoforming Specialist"},contacts:{phone:"+390119458087",email:"simone.laraia@aunde.com",linkedin:"https://www.linkedin.com/in/simone-laraia-b261567b/",vcard:"contact.vcf"},labels:{addContact:"Aggiungi ai contatti",call:"Chiama",email:"Email",linkedin:"LinkedIn",footer:"SL Identity",toast:"Contatto pronto per essere aggiunto"}};
const $=id=>document.getElementById(id);
function mergeProfile(profile={}){return{identity:{...FALLBACK_PROFILE.identity,...(profile.identity||{})},branding:{...FALLBACK_PROFILE.branding,...(profile.branding||{})},role:{...FALLBACK_PROFILE.role,...(profile.role||{})},contacts:{...FALLBACK_PROFILE.contacts,...(profile.contacts||{})},labels:{...FALLBACK_PROFILE.labels,...(profile.labels||{})}}}
function getProfileId(){const params=new URLSearchParams(window.location.search);return params.get("id")||"simone"}
function getCleanProfileUrl(){const id=getProfileId();return `${window.location.origin}${window.location.pathname}?id=${encodeURIComponent(id)}`}
async function fetchJson(file){const response=await fetch(file,{cache:"no-store"});if(!response.ok)throw new Error(`${file} non disponibile`);return response.json()}
async function loadProfile(){const id=getProfileId();const file=`profiles/${id}.json`;try{return mergeProfile(await fetchJson(file))}catch(e){try{return mergeProfile(await fetchJson("profile.json"))}catch(err){return FALLBACK_PROFILE}}}
function setText(id,value){const el=$(id);if(el)el.textContent=value||""}
function setHref(id,value){const el=$(id);if(el&&value)el.href=value}
function applyProfile(p){document.title=p.identity.name||"SL Identity";const color=p.identity.themeColor||"#233F91";document.documentElement.style.setProperty("--blue",color);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute("content",color);const logo=$("logo");if(logo){logo.src=p.branding.logo||p.identity.logo||FALLBACK_PROFILE.identity.logo;logo.alt=p.branding.company||p.identity.company||"Logo"}setText("name",p.identity.name);setText("departmentIt",p.role.departmentIt);setText("departmentEn",p.role.departmentEn);setText("roleIt",p.role.titleIt);setText("roleEn",p.role.titleEn);setHref("contactLink",p.contacts.vcard);setHref("phoneLink",`tel:${p.contacts.phone}`);setHref("emailLink",`mailto:${p.contacts.email}`);setHref("linkedinLink",p.contacts.linkedin);setText("addContactLabel",p.labels.addContact);setText("callLabel",p.labels.call);setText("emailLabel",p.labels.email);setText("linkedinLabel",p.labels.linkedin);setText("footer",p.labels.footer);setText("toast",p.labels.toast)}
function vibrate(ms=8){if(navigator.vibrate)navigator.vibrate(ms)}
function showToast(text){const toast=$("toast");if(!toast)return;toast.textContent=text||"Operazione completata";toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1800)}
async function showQrModal(){const modal=$("qrModal"),box=$("qrCanvas"),download=$("qrDownload");if(!modal||!box||!download)return;box.innerHTML="";if(!window.QRCode){showToast("QR non disponibile");return}const canvas=document.createElement("canvas");await QRCode.toCanvas(canvas,getCleanProfileUrl(),{width:230,margin:2,errorCorrectionLevel:"H"});box.appendChild(canvas);download.href=canvas.toDataURL("image/png");modal.hidden=false}
function hideQrModal(){const modal=$("qrModal");if(modal)modal.hidden=true}
function bindInteractions(p){document.querySelectorAll(".button").forEach(b=>b.addEventListener("click",()=>vibrate(8)));const c=document.querySelector("[data-contact]");if(c)c.addEventListener("click",()=>{vibrate(12);showToast(p.labels.toast)});const q=$("qrButton");if(q)q.addEventListener("click",showQrModal);const close=$("qrClose");if(close)close.addEventListener("click",hideQrModal);const modal=$("qrModal");if(modal)modal.addEventListener("click",e=>{if(e.target===modal)hideQrModal()})}
async function init(){const p=await loadProfile();applyProfile(p);bindInteractions(p);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})}
document.addEventListener("DOMContentLoaded",init);