const FALLBACK_PROFILE={identity:{name:"Simone Laraia",company:"AUNDE Italia",logo:"assets/logo/ultimo-logo.png",themeColor:"#233F91"},branding:{logo:"assets/logo/ultimo-logo.png",company:"AUNDE Italia",website:"https://aunde.com"},role:{departmentIt:"Ente Tecnico",departmentEn:"Technical Department",titleIt:"Tecnico di termoformatura",titleEn:"Fabric Thermoforming Specialist"},contacts:{phone:"+390119458087",email:"simone.laraia@aunde.com",linkedin:"https://www.linkedin.com/in/simone-laraia-b261567b/",vcard:"contact.vcf"},labels:{addContact:"Aggiungi ai contatti",call:"Chiama",email:"Email",linkedin:"LinkedIn",footer:"SL Identity",toast:"Contatto pronto per essere aggiunto"}};
const $=id=>document.getElementById(id);
function mergeProfile(p={}){return{identity:{...FALLBACK_PROFILE.identity,...(p.identity||{})},branding:{...FALLBACK_PROFILE.branding,...(p.branding||{})},role:{...FALLBACK_PROFILE.role,...(p.role||{})},contacts:{...FALLBACK_PROFILE.contacts,...(p.contacts||{})},labels:{...FALLBACK_PROFILE.labels,...(p.labels||{})}}}
async function loadProfile(){try{const r=await fetch("profile.json",{cache:"no-store"});if(!r.ok)throw new Error("profile.json non disponibile");return mergeProfile(await r.json())}catch(e){console.warn("SL Identity: uso dati fallback",e);return FALLBACK_PROFILE}}
function setText(id,v){const el=$(id);if(el)el.textContent=v||""}
function setHref(id,v){const el=$(id);if(el&&v)el.href=v}
function applyProfile(p){document.title=p.identity.name||"SL Identity";const color=p.identity.themeColor||"#233F91";document.documentElement.style.setProperty("--blue",color);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute("content",color);const logo=$("logo");if(logo){logo.src=p.branding.logo||p.identity.logo;logo.alt=p.branding.company||p.identity.company||"Logo"}setText("name",p.identity.name);setText("departmentIt",p.role.departmentIt);setText("departmentEn",p.role.departmentEn);setText("roleIt",p.role.titleIt);setText("roleEn",p.role.titleEn);setHref("contactLink",p.contacts.vcard);setHref("phoneLink",`tel:${p.contacts.phone}`);setHref("emailLink",`mailto:${p.contacts.email}`);setHref("linkedinLink",p.contacts.linkedin);setText("addContactLabel",p.labels.addContact);setText("callLabel",p.labels.call);setText("emailLabel",p.labels.email);setText("linkedinLabel",p.labels.linkedin);setText("footer",p.labels.footer);setText("toast",p.labels.toast);window.SL_IDENTITY_PROFILE=p}
function vibrate(ms=8){if(navigator.vibrate)navigator.vibrate(ms)}
function showToast(text){const t=$("toast");if(!t)return;t.textContent=text;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),1800)}
async function init(){const p=await loadProfile();applyProfile(p);document.querySelectorAll(".button").forEach(b=>b.addEventListener("click",()=>vibrate(8)));const c=document.querySelector("[data-contact]");if(c)c.addEventListener("click",()=>{vibrate(12);showToast(p.labels.toast)});if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})}
document.addEventListener("DOMContentLoaded",init);
